apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multi-platform-test
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/arewm-tenant/multi-platform-test/multi-platform-test@sha256:b2d87eb0671f9d96645af650030b5ff46d87d0a46acd749f5514ccdb0d5795a4
        name: my-go
        resources: {}
status: {}
